from smolagents import tool

@tool
def generate_lyrics(prompt: str, style: str = "hip-hop", length: int = 16) -> str:
    """Generate AI lyrics."""
    return f"🎵 Generated {style} lyrics for '{prompt}':\n\n[Verse 1]\n{ prompt } flow...\n(Full lyrics generated by agent LLM)"
